name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build, test, and code coverage
      run: make
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: 9133ad2d68de2dc6b70abdb4ced9232b
        filename: MotionCollector-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
